name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        cd Gamepedia
        pod install --repo-update
      shell: bash
      
    - name: Build and test
      run: xcodebuild clean build test -workspace Gamepedia/Gamepedia.xcworkspace -scheme Gamepedia -derivedDataPath Build/ -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' build test
      
    - name: Create code coverage report
      run: bash xccov-to-sonarqube-generic.sh Build/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
      
    - name: Upload Coverage Report to Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: sonarqube-generic-coverage.xml
        
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    needs: [build-and-test]
    
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Download Coverage Report from Artifact
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
      
    - name: Install Sonar Scanner
      run: brew install sonar-scanner

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -X
