name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        cd Gamepedia
        pod install --repo-update
      shell: bash
    - name: Build and test
      run: xcodebuild clean build test -workspace Gamepedia/Gamepedia.xcworkspace -scheme Gamepedia -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' build test
